# Name of the GitHub Action workflow
name: Deploy Frontend to GitHub Pages

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Sets the permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Replaces a placeholder in your index.html with the zrok URL from secrets
      - name: Configure Backend URL
        run: |
          # This command finds the placeholder and replaces it with your secret URL.
          # The '|' character is used as a separator to avoid issues with URLs containing slashes.
          sed -i 's|__BACKEND_URL__|${{ secrets.ZROK_URL }}/api/chat|g' index.html
        # This step is conditional and will only run if the secret is set.
        if: secrets.ZROK_URL != ''

      # 3. Sets up the GitHub Pages environment
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 4. Uploads the static files as a build artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the entire repository (since it's just the frontend)
          path: '.'

      # 5. Deploys the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4