# Name of the GitHub Action workflow
name: Deploy Frontend to GitHub Pages

# Controls when the action will run
on:
  # Triggers the workflow on push events to the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This step now uses the NGROK_API_URL secret
      - name: Configure Backend URL
        run: |
          if [ -n "${{ secrets.NGROK_API_URL }}" ]; then
            echo "✅ NGROK_API_URL secret found. Configuring backend URL..."
            sed -i 's|__BACKEND_URL__|${{ secrets.NGROK_API_URL }}|g' index.html
          else
            echo "⚠️ NGROK_API_URL secret is not set. Build will fail."
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4